# Generated by Django 3.1.2 on 2020-10-25 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckListTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(blank=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Display order')),
                ('activity', models.ManyToManyField(to='business.Activity')),
            ],
            options={
                'verbose_name': 'Checklist Tab',
                'verbose_name_plural': 'Checklist Tabs',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.SmallIntegerField(choices=[(0, 'Low Danger'), (1, 'Middle Danger'), (2, 'High Danger')], verbose_name='Display method')),
                ('branch_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='business.branchstore', verbose_name='Branch Store')),
                ('inspectors', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Inspectors')),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('inspection_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Inspection unique identifier')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='checklist.inspection', verbose_name='Inspection')),
                ('inspectors', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Inspectors')),
            ],
            options={
                'verbose_name': 'Set of answers to Inspection Checklist',
                'verbose_name_plural': 'Set of answers to Inspection Checklists',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='CheckListTabItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('text', 'text'), ('radio', 'radio'), ('select', 'select'), ('checkbox', 'checkbox'), ('select_image', 'Select Image'), ('integer', 'integer'), ('float', 'float'), ('date', 'date')], default='text', max_length=100, verbose_name='Type')),
                ('choices', models.TextField(blank=True, help_text="\n    The choices field is only used if the question type is 'radio', 'select', or \n    'select multiple' provide a comma-separated list of options for this question.\n    ", null=True, verbose_name='Choices')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Display order')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('is_important', models.BooleanField(blank=True, verbose_name='Is Important')),
                ('inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='checklist.inspection', verbose_name='Inspection')),
                ('tab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='checklist.checklisttab', verbose_name='Tab')),
            ],
            options={
                'verbose_name': 'Checklist Tab Item',
                'verbose_name_plural': 'Checklist Tabs Items',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='checklisttab',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabs', to='checklist.inspection', verbose_name='Inspection'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Choice')),
                ('check_list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='checklist.checklisttabitem', verbose_name='Checklist Item')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='checklist.response', verbose_name='Response')),
            ],
        ),
    ]
