# Generated by Django 3.1.2 on 2020-10-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AddField(
            model_name='activity',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Display order'),
        ),
    ]
