# Generated by Django 3.1.2 on 2020-10-24 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_typeofactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckListTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.activity')),
            ],
            options={
                'verbose_name': 'Checklist Tab',
                'verbose_name_plural': 'Checklist Tabs',
            },
        ),
    ]
