# Generated by Django 3.1.2 on 2020-10-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_checklisttab'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttab',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Display order'),
        ),
        migrations.RemoveField(
            model_name='checklisttab',
            name='activity',
        ),
        migrations.AddField(
            model_name='checklisttab',
            name='activity',
            field=models.ManyToManyField(to='checklist.Activity'),
        ),
    ]
