# Generated by Django 3.1.2 on 2020-10-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='RegionUnity',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='ZipCode',
        ),
    ]
