# Generated by Django 3.1.2 on 2020-10-25 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(blank=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Display order')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='TypeOfActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.activity')),
            ],
            options={
                'verbose_name': 'Type of Activity',
                'verbose_name_plural': 'Type of Activities',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('vat', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BranchStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('notify_number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('address_number', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=150)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branchstores', to='business.activity')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branchstores', to='business.business')),
                ('health_regulator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branchstores', to='regions.region')),
                ('region_unity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branchstores', to='regions.regionunity')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branchstores', to='regions.state')),
                ('type_of_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branchstores', to='business.typeofactivity')),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branchstores', to='regions.zipcode')),
            ],
        ),
    ]
