# Generated by Django 3.1.2 on 2020-10-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='VAT',
            field=models.PositiveIntegerField(),
        ),
    ]
