# Generated by Django 3.1.2 on 2020-10-24 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_region_regionunity_state_zipcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0004_auto_20201024_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('notify_number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('address_number', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=150)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='business.business')),
                ('health_regulator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.region')),
                ('region_unity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.regionunity')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.state')),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.zipcode')),
            ],
        ),
    ]
